package com.podevs.android.pokemononline.battle;

public enum BattleCommand {
    SendOut,
    SendBack,
    UseAttack,
    OfferChoice,
    BeginTurn,
    ChangePP,
    ChangeHp,
    Ko,
    Effective, /* to tell how a move is effective */
    Miss,
    CriticalHit, // = 10,
    Hit, /* for moves like fury double kick etc. */
    StatChange,
    StatusChange,
    StatusMessage,
    Failed,
    BattleChat,
    MoveMessage,
    ItemMessage,
    NoOpponent,
    Flinch, // = 20,
    Recoil,
    WeatherMessage,
    StraightDamage,
    AbilityMessage,
    AbsStatusChange,
    Substitute,
    BattleEnd,
    BlankMessage,
    CancelMove,
    Clause, // = 30,
    DynamicInfo, // = 31,
    DynamicStats, // = 32,
    Spectating,
    SpectatorChat,
    AlreadyStatusMessage,
    TempPokeChange,
    ClockStart, // = 37,
    ClockStop, // = 38,
    Rated,
    TierSection, // = 40,
    EndMessage,
    PointEstimate,
    MakeYourChoice,
    Avoid,
    RearrangeTeam,
    SpotShifts,
    CappedStat
}
